# Generated by Django 4.2.1 on 2023-07-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appsuscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
