# Generated by Django 4.2.1 on 2023-07-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appsuscripciones', '0003_suscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'suscripcion', 'verbose_name_plural': 'suscripciones'},
        ),
        migrations.AlterModelTable(
            name='suscripcion',
            table='detalle_suscripcion',
        ),
    ]
