# Generated by Django 4.2.1 on 2023-07-03 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appsuscripciones', '0004_alter_suscripcion_options_alter_suscripcion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
