# Generated by Django 4.2.1 on 2023-07-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0002_alter_direccion_cod_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.IntegerField()),
                ('fec_ini', models.DateField()),
                ('fec_ter', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='App.articulo')),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
                'db_table': 'descuento',
            },
        ),
    ]
